plugins:
  - jekyll-feed
title: Zhao Song's Blog
author: songzhao.asm@icloud.com
description: Database internals

highlighter: null
permalink: /:title

url: "https://kernelmaker.github.io"
baseurl:

sass:
  sass_dir: public/css
  style: :compressed
